#!/usr/bin/env python3
"""Write paper/lonely_numbers.tex from results/summary_lonely.json."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def fmt(x: float, nd: int = 3) -> str:
    return f"{x:.{nd}f}"


def main() -> None:
    s = json.loads((ROOT / "results" / "summary_lonely.json").read_text())["payload"]
    ex = s["headline_exact"]
    h = s["headline_mc"]
    k1 = s["kill_q1_mc"]
    rh = s["rho05_mc"]
    match = s["match_floor"]["p0.7"]
    over = {round(float(r["m"]), 2): r for r in s["overinvite_p07"]}
    fr_dyad0 = s["frailty"]["k2_rho0.0"]
    fr_dyad5 = s["frailty"]["k2_rho0.5"]
    fr_pub5 = s["frailty"]["k24_rho0.5"]

    macros = {
        "LonelyNOk": str(s["n_ok"]),
        "LonelyNFailed": str(s["n_failed"]),
        "LonelySeconds": fmt(s["seconds"], 1),
        "LonelyNSeeds": str(h["delta_alone_mc"]["n"]),
        "LonelyP": fmt(ex["p"], 2),
        "LonelyKDyad": str(ex["k_dyad"]),
        "LonelyKDinner": str(ex["k_dinner"]),
        "LonelyKPub": str(ex["k_pub"]),
        "LonelyAloneDyad": fmt(ex["alone_dyad"]),
        "LonelyAloneDinner": fmt(ex["alone_dinner"]),
        "LonelyAlonePub": fmt(ex["alone_pub"]),
        "LonelyDeltaExact": fmt(ex["delta_dyad_pub"]),
        "LonelyDeltaDinner": fmt(ex["delta_dinner_pub"]),
        "LonelyExtraDyad": fmt(ex["extra_dyad"]),
        "LonelyExtraPub": fmt(ex["extra_pub"]),
        "LonelyFloor": fmt(ex["own_flake_floor"]),
        "LonelyKillDelta": fmt(ex["kill_q1_delta"]),
        "LonelyKillDyad": fmt(ex["kill_q1_dyad"]),
        "LonelyKillPub": fmt(ex["kill_q1_pub"]),
        "LonelyQualityExact": fmt(ex["quality_shift_exact"]),
        "LonelyDeltaMc": fmt(h["delta_alone_mc"]["mean"]),
        "LonelyDeltaMcStd": fmt(h["delta_alone_mc"]["std"]),
        "LonelyDyadMc": fmt(h["dyad_alone"]["mean"]),
        "LonelyPubMc": fmt(h["pub_alone"]["mean"]),
        "LonelyQualityMc": fmt(h["quality_delta"]["mean"]),
        "LonelyQualityMcStd": fmt(h["quality_delta"]["std"]),
        "LonelyInspAtt": fmt(h["insp_att"]["mean"]),
        "LonelyInspAttStd": fmt(h["insp_att"]["std"]),
        "LonelyInspEvent": fmt(h["insp_event"]["mean"]),
        "LonelyFeedAtt": fmt(h["feed_att"]["mean"]),
        "LonelyFeedEvent": fmt(h["feed_event"]["mean"]),
        "LonelyProposed": fmt(h["mean_proposed"]["mean"], 1),
        "LonelyShareOutLarge": fmt(h["share_out_large"]["mean"]),
        "LonelySharePeopleLarge": fmt(h["share_people_large"]["mean"]),
        "LonelyFomoAtt": fmt(h["fomo_att"]["mean"]),
        "LonelyCompareStay": fmt(h["compare_stay"]["mean"], 1),
        "LonelyCompareSmallOut": fmt(h["compare_small_out"]["mean"], 1),
        "LonelyDyadCancel": fmt(h["dyad_cancel"]["mean"]),
        "LonelyPubCancel": fmt(h["pub_cancel"]["mean"]),
        "LonelyKillMcDelta": fmt(k1["delta_alone_mc"]["mean"]),
        "LonelyKillMcStd": fmt(k1["delta_alone_mc"]["std"]),
        "LonelyRhoDelta": fmt(rh["delta_alone_mc"]["mean"]),
        "LonelyRhoDeltaStd": fmt(rh["delta_alone_mc"]["std"]),
        "LonelyMatchN": str(match["n"]),
        "LonelyMatchAlone": fmt(match["p_alone"]),
        "LonelyOverbookAlone": fmt(over[3.0]["p_alone_overinvite"]),
        "LonelyOverbookN": str(int(over[3.0]["n_invited"])),
        "LonelyFrailtyDyadIndep": fmt(fr_dyad0["p_alone_mc"]),
        "LonelyFrailtyDyadCorr": fmt(fr_dyad5["p_alone_mc"]),
        "LonelyFrailtyPubCorr": fmt(fr_pub5["p_alone_mc"]),
        "LonelyNPeople": str(s["n_people"]),
        "LonelyNNights": str(s["n_nights"]),
    }
    lines = [
        "% Auto-generated by scripts/make_lonely_numbers.py. Do not edit.",
        "",
    ]
    for k, v in macros.items():
        lines.append(f"\\newcommand{{\\Num{k}}}{{{v}}}")
    out = ROOT / "paper" / "lonely_numbers.tex"
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out} n_macros={len(macros)}")


if __name__ == "__main__":
    main()
